### ISSUE TITLE
How to select all elements with both classes - .classA and .classB ?

### ISSUE THREAD

**Issue by rahgurung** [fregante/select-dom#11]
I am sorry if this is not the right place to ask this but doing something like
  

    select.all('.classA, .classB');  
  
doesn't works for me.

**Comment by fregante** [comment]
Yeah StackOverflow is the right place. `select.all` treats selectors like `document.querySelector`

In this case you'll need both classes together to select items that have both.

```js
select.all('.classA.classB');  
```
