### ISSUE TITLE
different behavior omitted vs undefined base element arg

### ISSUE THREAD

**Issue by jeffmcaffer** [fregante/select-dom#19]
Perhaps a bit of a nit but the behavior of, for example, `select.all` is different if you simply don't pass the base element (second arg) vs passing one that's the value `undefined`. My expectation was that if the arg is omitted, it's undefined and so would default to `document` (as per the doc) and if I do pass `undefined`, the second arg is still `undefined` and should default to `document`.

See https://github.com/fregante/select-dom/blob/master/index.ts#L99

The net is that at all my call sites I have to test the element being passed in and substitute `document` if the value is `undefined`. Certainly doable but a bit of a bummer.

I won't be upset if this is closes "wont fix" but thought I'd give the feedback.  Thanks for the handy library.

**Comment by fregante** [comment]
Thank you for the issue! You can refer to https://github.com/fregante/select-dom/issues/6

This behavior is also specified in the API section of the readme
