### ISSUE TITLE
Optional `baseElement` relies on arity

### ISSUE THREAD

**Issue by ngryman** [fregante/select-dom#6]
Hey @bfred-it,

It seems that you check the presence of `baseElement` by relying on function arity rather than checking its type (ie. `null` or `undefined`). I wonder if there is any reason to do that?

It seems a little odd to me that passing `undefined` as `baseElement` actually makes `select` scoping its selection to... nothing?

Here is an example to illustrate the issue. Let's say I want to abstract `select` from my consumer:

```ts
export const selectCssHook = (hook: CSSHook, baseElement?: Element) => {
  return select(`.${cssHookToClass(hook)}`, baseElement);
};
```

With the current implementation of `select`, the above function will fail when no `baseElement` is passed. I would expect not to. If I want `select` to work properly with no `baseElement`, I then need to rewrite it to something like:

```ts
export const selectCssHook = (hook: CSSHook, baseElement?: Element) => {
  return baseElement
    ? select(`.${cssHookToClass(hook)}`, baseElement)
    : select(`.${cssHookToClass(hook)}`);
};
```

Are you open to refactor this? I can open a PR if you want.

**Comment by fregante** [comment]
https://github.com/bfred-it/select-dom/commit/bd578b975e35d9f802cb43a900a6d3c83095c76a

**Comment by fregante** [comment]
What do you expect the result of this code to be?


```js
select(".a", select(".b"));
```

Is it the same as `.a .b`? Nope. If `select-dom` doesn't rely on arity and `.b` isn't found, `select` would look for `.a` on document, ignoring the `baseElement` parameter altogether.

That's probably never what you expect.

**Comment by fregante** [comment]
To solve your issue, use `...args` to pass the arguments, e.g.

```ts
export const selectCssHook = (hook: CSSHook, ...args) => {
  return select(`.${cssHookToClass(hook)}`, ...args);
};
```

**Comment by ngryman** [comment]
Thanks for the precisions!
